language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
install:
  - pip install -r requirements.txt
script:
  - python -m scrycli search jace vryn
  - python -m scrycli named jace vryn
  - python -m scrycli random 2
